# Generated by Django 3.2.18 on 2023-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icapp', '0002_tub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tub',
            name='tub_gluten',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Gluten free'),
        ),
        migrations.AlterField(
            model_name='tub',
            name='tub_vegan',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='Vegan'),
        ),
    ]
