# Generated by Django 3.2.18 on 2023-03-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icapp', '0003_auto_20230323_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tub',
            old_name='tub_store',
            new_name='store',
        ),
    ]
