# Generated by Django 3.2.18 on 2023-03-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icapp', '0004_rename_tub_store_tub_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tub',
            name='tub_size',
            field=models.FloatField(),
        ),
    ]
